name: village9991
favicon: null
layout_spectrum: 0.50933
typography_spectrum: 0.17957
title: village9991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030409'
    - '#363f48'
    - '#bb7804'
    - '#fdf8f4'
    - '#b09d71'
  brandStrength: 0.8818077279720455
  lightness: 0.5077843349426985
  saturation: 0.9460414685308933
  rhythmicContrast: 0.9416095509659499
purpose: []
